# Generated by Django 4.2.6 on 2023-10-18 15:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(default=None)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("can_renovate", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Alocation",
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="book",
            name="deleted_at",
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.CharField(blank=True, max_length=455),
        ),
        migrations.AddField(
            model_name="book",
            name="edition",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="book",
            name="quantity",
            field=models.PositiveIntegerField(
                default=0, help_text="Quantity available for allocation"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="rating",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=2
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="client",
            name="address",
            field=models.CharField(blank=True, max_length=355),
        ),
        migrations.AddField(
            model_name="client",
            name="cpf",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name="client",
            name="deleted_at",
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name="client",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="client",
            name="tel",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="allocation",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="core.book",
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="core.client",
            ),
        ),
    ]
