# Generated by Django 4.2.6 on 2023-10-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_book_isbestseller_alter_book_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allocation",
            name="deleted_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="deleted_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="deleted_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
